### PR TITLE
Endpoint definitions

### PR DESCRIPTION
**Pull request by SalmanAsh**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/8)

### CODE REVIEW

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 17 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/8)* status: 17 of 21 files reviewed, all discussions resolved (waiting on @SalmanAsh)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/8)* status: all files reviewed, 1 unresolved discussion (waiting on @SalmanAsh)

___
*[`src/pages/agreementSignatureDetails/AgreementSignatureDetails.tsx` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/8#-O5mMpk771IY9Z592kFa:-O5mMpk771IY9Z592kFb:bu96hje) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/b6a114647aa9c08ad87d82b5bfa39bf2ea386d0e/src/pages/agreementSignatureDetails/AgreementSignatureDetails.tsx#L1)):*
> ```XML
> import * as pages from "codeforlife/components/page"
> ```

If this page (and the other 3) were for testing purposes, please remove them from this PR.

**Review by SalmanAsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/8)* status: 17 of 21 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`src/pages/agreementSignatureDetails/AgreementSignatureDetails.tsx` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/8#-O5mMpk771IY9Z592kFa:-O5n-RJ3A3VhNwbkvjYU:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/b6a114647aa9c08ad87d82b5bfa39bf2ea386d0e/src/pages/agreementSignatureDetails/AgreementSignatureDetails.tsx#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

If this page (and the other 3) were for testing purposes, please remove them from this PR.
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/8#-:-O5n0a8B-5YJfhAXRM1G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SalmanAsh)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SalmanAsh)

**Pull request merged**
